version: '3.4'

services:
  edwardhsu.lab.migratekafkaevent:
    image: ${DOCKER_REGISTRY-}edwardhsulabmigratekafkaevent
    depends_on:
      - kafka1
      - kafka2
    build:
      context: .
      dockerfile: EdwardHsu.Lab.MigrateKafkaEvent/Dockerfile
  kafka1:
    image: docker.vectorized.io/vectorized/redpanda:v21.7.6
    command: ["redpanda", "start",
        "--kafka-addr", "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092",
        "--advertise-kafka-addr", "PLAINTEXT://kafka1:29092,OUTSIDE://kafka1:9092"]
    ports:
      - 9092:9092
      - 29092:29092
  kafka2:
    image: docker.vectorized.io/vectorized/redpanda:v21.7.6
    command: ["redpanda", "start",
        "--kafka-addr", "PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093",
        "--advertise-kafka-addr", "PLAINTEXT://kafka2:29093,OUTSIDE://kafka2:9093"]
    ports:
      - 9093:9093
      - 29093:29093